name: Build and Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache-dependency-path: synora-gateway/go.sum

    - name: Build
      run: cd synora-gateway && go build -v ./...

    - name: Test
      run: cd synora-gateway && go test -v ./...

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push Docker image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: ./synora-gateway
        file: ./synora-gateway/deploy/Dockerfile
        push: true
        tags: |
          larrychen0125/synora:latest
          larrychen0125/synora:${{ github.sha }}
